PROCESS BEFORE OUTPUT.
  MODULE status_0200.
  CALL SUBSCREEN ss1 INCLUDING sy-cprog '0210'.
  CALL SUBSCREEN ss2 INCLUDING sy-cprog '0220'.

*
PROCESS AFTER INPUT.
  MODULE user_command_0200.

  CALL SUBSCREEN ss1.
  CALL SUBSCREEN ss2.
